export const News = [
    {
        id: 1,
        title: "Lễ đầy tháng 2 Hổ Bengal con 1",
        content: "Tại Thảo Cầm Viên Sài Gòn, việc nhân giống bảo tồn các loài động vật quý hiếm có nguy cơ bị tuyệt chủng luôn được Ban Lãnh đạo Công ty chú trọng ưu tiên hàng đầu nhằm đẩy mạnh công tác bảo tồn trong điều kiện nuôi, góp phần tuyên truyền bảo vệ các loài động vật quý hiếm đang bị đe dọa tuyệt chủng đến các em học sinh và người dân trên cả nước. Trong đó, việc nhân giống cho sinh sản đàn hổ luôn được quan tâm nhất, nhằm gia tăng số lượng đàn hổ, đảm bảo giữ nguồn gen thuần góp phần bảo tồn một cách bền vững loài Hổ. ​Năm 2014, Thảo Cầm Viên Sài Gòn lần đầu tiên đã cho sinh sản thành công 05 cá thể Hổ Đông Dương, 04 cá thể Hổ Bengal trong điểu kiện nuôi. Và tiếp tục đến năm 2015, Thảo Cầm Viên Sài Gòn tiếp tục cho sinh sản thành công 02 cá thể hổ Bengal trắng sau khoảng một thời gian dài nổ lực không ngừng của cả tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên bộ phận chuyên môn trong công tác nhân giống bảo tồn. ​Tiếp nối những thành quả đạt được, tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên Xí Nghiệp Động vật tiếp tục triển khai thực hiện công tác nhân giống sinh sản các loài động vật quý hiếm. Cuối cùng, sự nỗ lực cố gắng ấy đã đạt kết quả tốt trong sự vui mừng của tập thể Cán bộ Công nhân viên Thảo Cầm Viên Sài Gòn nói chung và Cán bộ công nhân viên Xí nghiệp Động vật nói riêng khi 02 cá thể hổ Bengal con đã chào đời vào ngày 13/5/2023 tại Thảo Cầm Viên Sài Gòn. ​Thành công của ngày hôm nay là sự kết hợp giữa công tác cứu hộ động vật và công tác nhân giống bảo tồn loài hổ của TCVSG. Cha của 02 cá thể hổ Bengal con là hổ Bengal đực được sinh ra tại TCVSG vào năm 2014, mẹ của 02 cá thể hổ Bengal con là 01 trong 04 cá thể hổ Bengal mà TCVSG đã tiếp nhận cứu hộ từ Chi cục Kiểm Lâm tỉnh Bình Dương chuyển giao chăm sóc nuôi dưỡng vào ngày 23/02/2022.",
        thumbnailUrl: "https://saigonzoo.net/wp-content/uploads/2023/06/z4428572536712_4de203fab08913e4ed392a2568c11db2.jpg",
        createdDate: "11/11/2023",
    },
    {
        id: 2,
        title: "Lễ đầy tháng 2 Hổ Bengal con 2",
        content: "Tại Thảo Cầm Viên Sài Gòn, việc nhân giống bảo tồn các loài động vật quý hiếm có nguy cơ bị tuyệt chủng luôn được Ban Lãnh đạo Công ty chú trọng ưu tiên hàng đầu nhằm đẩy mạnh công tác bảo tồn trong điều kiện nuôi, góp phần tuyên truyền bảo vệ các loài động vật quý hiếm đang bị đe dọa tuyệt chủng đến các em học sinh và người dân trên cả nước. Trong đó, việc nhân giống cho sinh sản đàn hổ luôn được quan tâm nhất, nhằm gia tăng số lượng đàn hổ, đảm bảo giữ nguồn gen thuần góp phần bảo tồn một cách bền vững loài Hổ. ​Năm 2014, Thảo Cầm Viên Sài Gòn lần đầu tiên đã cho sinh sản thành công 05 cá thể Hổ Đông Dương, 04 cá thể Hổ Bengal trong điểu kiện nuôi. Và tiếp tục đến năm 2015, Thảo Cầm Viên Sài Gòn tiếp tục cho sinh sản thành công 02 cá thể hổ Bengal trắng sau khoảng một thời gian dài nổ lực không ngừng của cả tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên bộ phận chuyên môn trong công tác nhân giống bảo tồn. ​Tiếp nối những thành quả đạt được, tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên Xí Nghiệp Động vật tiếp tục triển khai thực hiện công tác nhân giống sinh sản các loài động vật quý hiếm. Cuối cùng, sự nỗ lực cố gắng ấy đã đạt kết quả tốt trong sự vui mừng của tập thể Cán bộ Công nhân viên Thảo Cầm Viên Sài Gòn nói chung và Cán bộ công nhân viên Xí nghiệp Động vật nói riêng khi 02 cá thể hổ Bengal con đã chào đời vào ngày 13/5/2023 tại Thảo Cầm Viên Sài Gòn. ​Thành công của ngày hôm nay là sự kết hợp giữa công tác cứu hộ động vật và công tác nhân giống bảo tồn loài hổ của TCVSG. Cha của 02 cá thể hổ Bengal con là hổ Bengal đực được sinh ra tại TCVSG vào năm 2014, mẹ của 02 cá thể hổ Bengal con là 01 trong 04 cá thể hổ Bengal mà TCVSG đã tiếp nhận cứu hộ từ Chi cục Kiểm Lâm tỉnh Bình Dương chuyển giao chăm sóc nuôi dưỡng vào ngày 23/02/2022.",
        thumbnailUrl: "https://saigonzoo.net/wp-content/uploads/2023/06/z4428572536712_4de203fab08913e4ed392a2568c11db2.jpg",
        createdDate: "11/11/2023",
    },
    {
        id: 3,
        title: "Lễ đầy tháng 2 Hổ Bengal con 3",
        content: "Tại Thảo Cầm Viên Sài Gòn, việc nhân giống bảo tồn các loài động vật quý hiếm có nguy cơ bị tuyệt chủng luôn được Ban Lãnh đạo Công ty chú trọng ưu tiên hàng đầu nhằm đẩy mạnh công tác bảo tồn trong điều kiện nuôi, góp phần tuyên truyền bảo vệ các loài động vật quý hiếm đang bị đe dọa tuyệt chủng đến các em học sinh và người dân trên cả nước. Trong đó, việc nhân giống cho sinh sản đàn hổ luôn được quan tâm nhất, nhằm gia tăng số lượng đàn hổ, đảm bảo giữ nguồn gen thuần góp phần bảo tồn một cách bền vững loài Hổ. ​Năm 2014, Thảo Cầm Viên Sài Gòn lần đầu tiên đã cho sinh sản thành công 05 cá thể Hổ Đông Dương, 04 cá thể Hổ Bengal trong điểu kiện nuôi. Và tiếp tục đến năm 2015, Thảo Cầm Viên Sài Gòn tiếp tục cho sinh sản thành công 02 cá thể hổ Bengal trắng sau khoảng một thời gian dài nổ lực không ngừng của cả tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên bộ phận chuyên môn trong công tác nhân giống bảo tồn. ​Tiếp nối những thành quả đạt được, tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên Xí Nghiệp Động vật tiếp tục triển khai thực hiện công tác nhân giống sinh sản các loài động vật quý hiếm. Cuối cùng, sự nỗ lực cố gắng ấy đã đạt kết quả tốt trong sự vui mừng của tập thể Cán bộ Công nhân viên Thảo Cầm Viên Sài Gòn nói chung và Cán bộ công nhân viên Xí nghiệp Động vật nói riêng khi 02 cá thể hổ Bengal con đã chào đời vào ngày 13/5/2023 tại Thảo Cầm Viên Sài Gòn. ​Thành công của ngày hôm nay là sự kết hợp giữa công tác cứu hộ động vật và công tác nhân giống bảo tồn loài hổ của TCVSG. Cha của 02 cá thể hổ Bengal con là hổ Bengal đực được sinh ra tại TCVSG vào năm 2014, mẹ của 02 cá thể hổ Bengal con là 01 trong 04 cá thể hổ Bengal mà TCVSG đã tiếp nhận cứu hộ từ Chi cục Kiểm Lâm tỉnh Bình Dương chuyển giao chăm sóc nuôi dưỡng vào ngày 23/02/2022.",
        thumbnailUrl: "https://saigonzoo.net/wp-content/uploads/2023/06/z4428572536712_4de203fab08913e4ed392a2568c11db2.jpg",
        createdDate: "11/11/2023",
    },
    {
        id: 4,
        title: "Lễ đầy tháng 2 Hổ Bengal con 4",
        content: "Tại Thảo Cầm Viên Sài Gòn, việc nhân giống bảo tồn các loài động vật quý hiếm có nguy cơ bị tuyệt chủng luôn được Ban Lãnh đạo Công ty chú trọng ưu tiên hàng đầu nhằm đẩy mạnh công tác bảo tồn trong điều kiện nuôi, góp phần tuyên truyền bảo vệ các loài động vật quý hiếm đang bị đe dọa tuyệt chủng đến các em học sinh và người dân trên cả nước. Trong đó, việc nhân giống cho sinh sản đàn hổ luôn được quan tâm nhất, nhằm gia tăng số lượng đàn hổ, đảm bảo giữ nguồn gen thuần góp phần bảo tồn một cách bền vững loài Hổ. ​Năm 2014, Thảo Cầm Viên Sài Gòn lần đầu tiên đã cho sinh sản thành công 05 cá thể Hổ Đông Dương, 04 cá thể Hổ Bengal trong điểu kiện nuôi. Và tiếp tục đến năm 2015, Thảo Cầm Viên Sài Gòn tiếp tục cho sinh sản thành công 02 cá thể hổ Bengal trắng sau khoảng một thời gian dài nổ lực không ngừng của cả tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên bộ phận chuyên môn trong công tác nhân giống bảo tồn. ​Tiếp nối những thành quả đạt được, tập thể Ban lãnh đạo Công ty và Cán bộ công nhân viên Xí Nghiệp Động vật tiếp tục triển khai thực hiện công tác nhân giống sinh sản các loài động vật quý hiếm. Cuối cùng, sự nỗ lực cố gắng ấy đã đạt kết quả tốt trong sự vui mừng của tập thể Cán bộ Công nhân viên Thảo Cầm Viên Sài Gòn nói chung và Cán bộ công nhân viên Xí nghiệp Động vật nói riêng khi 02 cá thể hổ Bengal con đã chào đời vào ngày 13/5/2023 tại Thảo Cầm Viên Sài Gòn. ​Thành công của ngày hôm nay là sự kết hợp giữa công tác cứu hộ động vật và công tác nhân giống bảo tồn loài hổ của TCVSG. Cha của 02 cá thể hổ Bengal con là hổ Bengal đực được sinh ra tại TCVSG vào năm 2014, mẹ của 02 cá thể hổ Bengal con là 01 trong 04 cá thể hổ Bengal mà TCVSG đã tiếp nhận cứu hộ từ Chi cục Kiểm Lâm tỉnh Bình Dương chuyển giao chăm sóc nuôi dưỡng vào ngày 23/02/2022.",
        thumbnailUrl: "https://saigonzoo.net/wp-content/uploads/2023/06/z4428572536712_4de203fab08913e4ed392a2568c11db2.jpg",
        createdDate: "11/11/2023",
    },
];